In [1]:
# pandas version
import pandas as pd
print(pd.__version__)

3.0.6

In [76]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

fuel_types = df['fuel_type'].unique()

print(fuel_types)

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [68]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [65]:
# Count missing values in just the fuel_type column
missing_fuel_count = df['fuel_type'].isna().sum()
print(f"Missing fuel types: {missing_fuel_count}")

# Count missing values in EVERY column of the DataFrame
print(df.isna().sum())

Missing fuel types: 0
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [69]:
max_efficiency = df['fuel_efficiency_mpg'].max()
print(f"The maximum fuel efficiency is: {max_efficiency}")

The maximum fuel efficiency is: 41.2

In [82]:
print(df['horsepower'].median())

print(df['horsepower'].mode()[0])

254.0
252.0

In [71]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [4]:
# numpy version 

import numpy as np
print(np.__version__)

2.5.3

In [5]:
np

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [10]:
print(a)

[ 1  2  3  5  7 12]

In [11]:
a[2]

np.int64(3)

In [12]:
print(a[2])

3

In [17]:
a[2] = 10

In [18]:
a[2]

np.int64(10)

In [19]:
a

array([ 1,  2, 10,  5,  7, 12])

In [20]:
np.arange(1,5)

array([1, 2, 3, 4])

In [22]:
np.linspace

In [26]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [27]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.ones([5,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [31]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [34]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
n[2,2] = 12

In [38]:
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 12]])

In [41]:
n[0,2] = 13

In [42]:
n

array([[ 1,  2, 13],
       [ 4,  5,  6],
       [ 7,  8, 12]])

In [44]:
n[2]

array([ 7,  8, 12])

In [45]:
n[1]

array([4, 5, 6])

In [46]:
n[0]

array([ 1,  2, 13])